FROM eliorsade/webserver-non-mac:1.0.1
CMD mkdir /var/www/webosmaster
CMD chmod -R 755 /var/www/webosmaster
COPY ./html /var/www/webosmaster
CMD a2ensite webosmaster.conf
CMD a2dissite 000-default.conf
CMD service apache2 reload
COPY ./html/ /var/www/webosmaster.ga/
